version: '3.7'

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/node/app'
      - 'server-node-modules:/home/node/app/node_modules'
    ports:
      - '3000:3000'
    command: npm start
    depends_on:
      - database

  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123456
    volumes:
      - 'sqlvolume:/var/opt/mssql'

volumes:
  sqlvolume:
  server-node-modules:
